_AeronauticoBundle_homepage:
    pattern:  /
    defaults: { _controller: AeronauticoBundle:Aeronave:list}
    
_AeronauticoBundle_new:
    pattern:  /new
    defaults: { _controller: AeronauticoBundle:Aeronave:new}  

_AeronauticoBundle_edit:
    pattern:  /edit/{id}
    defaults: { _controller: AeronauticoBundle:Aeronave:edit}  

_AeronauticoBundle_del:
    pattern:  /del/{id}
    defaults: { _controller: AeronauticoBundle:Aeronave:del}      

_AeronauticoBundle_show:
    pattern:  /show/{id}
    defaults: { _controller: AeronauticoBundle:Aeronave:show}        